name: WhatIs
version: ${pom.version}
author: Schmoller

description: WhatIs provides tools to find out what each plugin interfaces with.

main: au.com.addstar.whatis.WhatIs

softdepend: [WorldEdit]

permissions:
  whatis:
    default: op
  whatis.command:
    default: op
    children:
      whatis: true
  whatis.report:
    default: op
    children:
      whatis: true
  whatis.events:
    default: op
    children:
      whatis: true
  whatis.eventmonitor:
    default: op
    children:
      whatis: true

commands:
  whatis:
    description: Allows you to find lots of information.
    permission: whatis